name: synergy_test
epochs: 1 #153 #200
augment: 5
batchsize: 108
size: 96
cam_size: 960
backbone: unet
features: 32
train_samples_per_epoch: 50000
num_workers: 4
projhead: minimal_batchnorm
classhead: minimal
input_train:
#- /media/cangxiong/storage/datasets/Synergy_project_data/021221_C16-1_8bit_PFFC-BrightAdj.tif
#- /media/cangxiong/storage/datasets/Synergy_project_data/tarrow/hela/train/02
#- /media/cangxiong/storage/datasets/Synergy_project_data/021221_C16-1_8bit_PFFC-BrightAdj.tif
#- /media/cangxiong/storage/datasets/Synergy_project_data/tarrow/hela/test/01
#- data/hela/train/01
#- data/hela/train/02
#- data/hela/test/01
#- data/hela/test/02
split_train:
- - 0.0 # should be 0.0 and use all the training data available
  - 1.0
split_val:
- 0.0
- 1.0 #- 0.1
